FROM ubuntu:22.04

ENV WS="/root"
ENV ACADOS_SOURCE_DIR="/root/acados"
ENV LD_LIBRARY_PATH="/root/acados/lib"

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR ${WS}

RUN apt-get update && \
    apt-get install build-essential -y && \
    apt-get install cmake -y && \ 
    apt-get install wget -y && \
    apt-get install unzip -y && \
    apt-get install git -y && \
    apt-get install vim -y && \
    apt-get install python3-pip -y && \
    apt-get install libyaml-cpp-dev -y && \
    #apt install libeigen3-dev -y && \
    apt-get install ffmpeg -y && \
    apt-get install libpython3.10 -y && \
    apt-get install libx11-6 -y && \
    apt-get install libsm6 -y && \
    apt-get install libxt6 -y && \
    apt-get install libglib2.0-0 -y && \
    apt-get install python3-sphinx -y && \
    apt-get install python3-numpydoc -y && \
    apt-get install python3-sphinx-rtd-theme -y && \
    apt-get install python-is-python3 &&\
    apt-get install python3-virtualenv -y 

RUN git clone https://github.com/acados/acados.git \
    && cd acados \
    && git submodule update --recursive --init \
    && mkdir -p build \
    && cd build \
    && cmake -DACADOS_WITH_QPOASES=ON .. \
    && make install -j4

RUN wget -O Eigen.zip https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip
RUN unzip Eigen.zip
RUN cp -r eigen-3.4.0/Eigen /usr/local/include

#build DFKI double_pendulum stuff
COPY . ${WS}/double_pendulum/

RUN cd double_pendulum && \
        pip install -U pip && \
    	make install
        #make pythonfull
    #&& python -m pip install stable-baselines3==2.3.2 cloudpickle==3.0.0

#build acados


#CMD ["${WS}/Acados_MPC/acadosMpcTest.py"]
