FROM ubuntu:22.04

ENV WS="/root"
ENV ACADOS_SOURCE_DIR="/root/acados"
ENV LD_LIBRARY_PATH="/root/acados/lib"

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR ${WS}

RUN apt-get update && \
    apt-get install build-essential -y && \
    apt-get install cmake -y && \
    apt-get install wget -y && \
    apt-get install unzip -y && \
    apt-get install git -y && \
    apt-get install vim -y && \
    apt-get install python3-pip -y && \
    apt-get install libyaml-cpp-dev -y && \
    #apt install libeigen3-dev -y && \
    apt-get install ffmpeg -y && \
    apt-get install libpython3.10 -y && \
    apt-get install libx11-6 -y && \
    apt-get install libsm6 -y && \
    apt-get install libxt6 -y && \
    apt-get install libglib2.0-0 -y && \
    apt-get install python3-sphinx -y && \
    apt-get install python3-numpydoc -y && \
    apt-get install python3-sphinx-rtd-theme -y && \
    apt-get install python-is-python3 && \
    apt-get install python3-virtualenv -y && \
    apt-get install nano

#
RUN wget -O Eigen.zip https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip
RUN unzip Eigen.zip
RUN cp -r eigen-3.4.0/Eigen /usr/local/include

#build DFKI double_pendulum stuff
RUN git clone https://github.com/Maranderine/double_pendulum_acados_MPC.git

RUN cd double_pendulum_acados_MPC && \
        pip install -U pip && \
    	make install && \
        make python && \
        cd src/python && \
        pip install .  

RUN git clone https://github.com/acados/acados.git \
    && cd acados \
    && git submodule update --recursive --init \
    && mkdir -p build \
    && cd build \
    && cmake -DACADOS_WITH_QPOASES=ON ..\
    && make install -j4

RUN pip install --upgrade pip setuptools 

RUN pip install -e acados/interfaces/acados_template

